export type Painting = {
  slug: string;
  title: string;
  medium: string;
  dimensions: string;
  year?: string;
  collection?: string;
  image: string;
  width: number;
  height: number;
  alt: string;
  accent: string; // approximate dominant colour, used for card theming
};

export const paintings: Painting[] = [
  {
    slug: "redolence",
    title: "Redolence",
    medium: "Oil on canvas",
    dimensions: '14 x 15" (approx.)',
    image: "/images/gallery/redolence.png",
    width: 853,
    height: 848,
    alt: "Redolence, an olive-green biomorphic oil painting with a terracotta vessel and a pale calla-lily form, by Komal Hira",
    accent: "#7c8c46",
  },
  {
    slug: "the-beginning",
    title: "The Beginning",
    medium: "Oil on canvas, diptych",
    dimensions: '22.5 x 15" (approx.)',
    image: "/images/gallery/the-beginning.png",
    width: 900,
    height: 1231,
    alt: "The Beginning, a midnight-blue diptych oil painting with floating jewel-toned biomorphic fragments, by Komal Hira",
    accent: "#1c2540",
  },
  {
    slug: "untitled-rose-fish",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '10 x 18" (approx.)',
    image: "/images/gallery/untitled-rose-fish.png",
    width: 790,
    height: 478,
    alt: "Untitled fish-shaped oil painting in dusty rose with pale blue biomorphic forms and a watching eye, by Komal Hira",
    accent: "#b56b7c",
  },
  {
    slug: "solace-2",
    title: "Solace 2",
    medium: "Oil on canvas",
    dimensions: '18 x 22" (approx.)',
    image: "/images/gallery/solace-2.png",
    width: 823,
    height: 1078,
    alt: "Solace 2, a teal comma-shaped oil painting cradling a small blue-violet biomorphic form, by Komal Hira",
    accent: "#1f7a7a",
  },
  {
    slug: "untitled-lavender-column",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '27.5 x 11" (approx.)',
    image: "/images/gallery/untitled-lavender-column.png",
    width: 580,
    height: 1423,
    alt: "Tall lavender oil painting with pale faceted crystalline forms, by Komal Hira",
    accent: "#8f86ad",
  },
  {
    slug: "untitled-indigo-24",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '13 x 35" (approx.)',
    year: "2024",
    image: "/images/gallery/untitled-indigo-24.png",
    width: 450,
    height: 1224,
    alt: "Tall indigo oil painting with a cluster of jewel-toned biomorphic figures at its base, by Komal Hira",
    accent: "#4a4fa0",
  },
  {
    slug: "untitled-amber-boomerang",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '17 x 30" (approx.)',
    year: "2024",
    image: "/images/gallery/untitled-amber-boomerang.png",
    width: 1393,
    height: 808,
    alt: "Amber boomerang-shaped oil painting with a small figure and rose motif, by Komal Hira",
    accent: "#c98a3e",
  },
  {
    slug: "moment-of-feel-i",
    title: "The Moment of Feel I",
    medium: "Oil on canvas, diptych",
    dimensions: '8 x 18"',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Lahore",
    image: "/images/gallery/moment-of-feel-i.png",
    width: 748,
    height: 665,
    alt: "The Moment of Feel I, a teal diptych oil painting of two nested curved forms, by Komal Hira",
    accent: "#1f8a7a",
  },
  {
    slug: "moment-of-feel-ii",
    title: "The Moment of Feel II",
    medium: "Oil on canvas, diptych",
    dimensions: '(1) 1.6 x 6.5", (2) 12 x 14"',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Lahore",
    image: "/images/gallery/moment-of-feel-ii.png",
    width: 864,
    height: 1296,
    alt: "The Moment of Feel II, a plum-toned diptych oil painting pairing a small oval canvas with a larger heart-shaped canvas, by Komal Hira",
    accent: "#6b3f52",
  },
  {
    slug: "the-blue-sky",
    title: "The Blue Sky",
    medium: "Oil on canvas, diptych",
    dimensions: '8 x 16" each',
    year: "2023",
    collection: "Private collection",
    image: "/images/gallery/the-blue-sky.png",
    width: 1500,
    height: 1061,
    alt: "The Blue Sky, two teal wing-shaped oil paintings meeting at a point with feather and droplet motifs, by Komal Hira",
    accent: "#2f8fa6",
  },
  {
    slug: "sigh",
    title: "Sigh",
    medium: "Oil on canvas, diptych",
    dimensions: '12 x 36" and 8 x 12"',
    year: "2023",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/sigh.png",
    width: 341,
    height: 1024,
    alt: "Sigh, an emerald-green diptych oil painting with a dark rose and ribbon motif, by Komal Hira",
    accent: "#1f6b45",
  },
  {
    slug: "subliminal-self",
    title: "Subliminal Self",
    medium: "Oil on canvas",
    dimensions: '12 x 26" (approx.)',
    year: "2023",
    image: "/images/gallery/subliminal-self.png",
    width: 1500,
    height: 1000,
    alt: "Subliminal Self, an olive-green cloud-shaped oil painting with a small nested figure, by Komal Hira",
    accent: "#5c7a3a",
  },
  {
    slug: "solace",
    title: "Solace",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 13" and 9 x 13.5"',
    year: "2024",
    image: "/images/gallery/solace.png",
    width: 1000,
    height: 1500,
    alt: "Solace, a crimson diptych oil painting of two organic rounded forms, by Komal Hira",
    accent: "#7c2530",
  },
  {
    slug: "untitled-blush-diptych",
    title: "Untitled",
    medium: "Oil on canvas, diptych",
    dimensions: '12 x 18" and 8 x 12"',
    year: "2024",
    image: "/images/gallery/untitled-blush-diptych.png",
    width: 698,
    height: 1500,
    alt: "Untitled blush-pink diptych oil painting, an oval canvas above a rectangular canvas, by Komal Hira",
    accent: "#d9a8ac",
  },
  {
    slug: "untitled-mauve-disc",
    title: "Untitled",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 17" each',
    year: "2024",
    image: "/images/gallery/untitled-mauve-disc.png",
    width: 612,
    height: 408,
    alt: "Untitled mauve-brown disc-shaped diptych oil painting split into two sections, by Komal Hira",
    accent: "#6e4f52",
  },
  {
    slug: "mindfulness",
    title: "Mindfulness",
    medium: "Oil on canvas",
    dimensions: '24 x 24" (approx.)',
    year: "2023",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/mindfulness.png",
    width: 1053,
    height: 702,
    alt: "Mindfulness, an indigo oil painting with a small luminous figure and a red ribbon, by Komal Hira",
    accent: "#2b2f57",
  },
  {
    slug: "untitled-coral-column",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '8 x 48"',
    year: "2022",
    image: "/images/gallery/untitled-coral-column.png",
    width: 433,
    height: 577,
    alt: "Untitled tall coral diptych oil painting of two narrow columns, by Komal Hira",
    accent: "#c96b5c",
  },
  {
    slug: "moment-of-feel-iv",
    title: "The Moment of Feel IV",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 30" each',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/moment-of-feel-iv.png",
    width: 768,
    height: 1024,
    alt: "The Moment of Feel IV, a magenta diptych oil painting pairing a teardrop shape with an angular canvas, by Komal Hira",
    accent: "#9c2a5e",
  },
  {
    slug: "moment-of-feel-iii",
    title: "The Moment of Feel III",
    medium: "Oil on canvas",
    dimensions: '8 x 18" (approx.)',
    year: "2023",
    collection: "Private collection",
    image: "/images/gallery/moment-of-feel-iii.png",
    width: 840,
    height: 1120,
    alt: "The Moment of Feel III, a sky-blue curved oil painting with a small floral motif, by Komal Hira",
    accent: "#3f8fbf",
  },
  {
    slug: "untitled-cobalt-abstract",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '18 x 24"',
    year: "2022",
    image: "/images/gallery/untitled-cobalt-abstract.png",
    width: 842,
    height: 1152,
    alt: "Untitled dense cobalt-blue abstract oil painting of layered biomorphic forms, by Komal Hira",
    accent: "#274a7a",
  },
  {
    slug: "untitled-mauve-still-life",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '12 x 16"',
    year: "2022",
    image: "/images/gallery/untitled-mauve-still-life.png",
    width: 792,
    height: 1040,
    alt: "Untitled dusky mauve still-life oil painting of abstract floral and geometric forms, by Komal Hira",
    accent: "#8a5f66",
  },
  {
    slug: "untitled-forest-still-life",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '12 x 16"',
    year: "2022",
    image: "/images/gallery/untitled-forest-still-life.png",
    width: 633,
    height: 948,
    alt: "Untitled deep forest-green still-life oil painting with a single stem and small biomorphic forms, by Komal Hira",
    accent: "#22381f",
  },
  {
    slug: "untitled-gold-fragment",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '12 x 12"',
    year: "2022",
    image: "/images/gallery/untitled-gold-fragment.png",
    width: 853,
    height: 1280,
    alt: "Untitled gold oil painting with a cluster of biomorphic forms along the edge, by Komal Hira",
    accent: "#c99a3f",
  },
];

export function getPaintingBySlug(slug: string): Painting | undefined {
  return paintings.find((p) => p.slug === slug);
}
