export type Painting = {
  slug: string;
  title: string;
  medium: string;
  dimensions: string;
  year?: string;
  collection?: string;
  image: string;
  width: number;
  height: number;
  alt: string;
  accent: string; // approximate dominant colour, used for card theming
};

export const paintings: Painting[] = [
  {
    slug: "gallery-01",
    title: "The Beginning",
    medium: "Oil on canvas, diptych",
    dimensions: '22.5 x 15" (approx.)',
    image: "/images/gallery/gallery-01.jpg",
    width: 2117,
    height: 2117,
    alt: "The Beginning, an oil-on-canvas diptych by Komal Hira",
    accent: "#1c2540",
  },
  {
    slug: "gallery-02",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '10 x 18" (approx.)',
    image: "/images/gallery/gallery-02.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil painting by Komal Hira",
    accent: "#b56b7c",
  },
  {
    slug: "gallery-03",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '13 x 35" (approx.)',
    year: "2024",
    image: "/images/gallery/gallery-03.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil painting by Komal Hira, 2024",
    accent: "#4a4fa0",
  },
  {
    slug: "gallery-04",
    title: "Subliminal Self",
    medium: "Oil on canvas",
    dimensions: '12 x 26" (approx.)',
    year: "2023",
    image: "/images/gallery/gallery-04.jpg",
    width: 2117,
    height: 2117,
    alt: "Subliminal Self, an oil painting by Komal Hira, 2023",
    accent: "#5c7a3a",
  },
  {
    slug: "gallery-05",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '27.5 x 11" (approx.)',
    image: "/images/gallery/gallery-05.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil painting by Komal Hira",
    accent: "#8f86ad",
  },
  {
    slug: "gallery-06",
    title: "Solace",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 13" and 9 x 13.5" (approx.)',
    year: "2024",
    image: "/images/gallery/gallery-06.jpg",
    width: 2117,
    height: 2117,
    alt: "Solace, an oil-on-canvas diptych by Komal Hira, 2024",
    accent: "#7c2530",
  },
  {
    slug: "gallery-07",
    title: "Redolence",
    medium: "Oil on canvas",
    dimensions: '14 x 15" (approx.)',
    image: "/images/gallery/gallery-07.jpg",
    width: 2117,
    height: 2117,
    alt: "Redolence, an oil painting by Komal Hira",
    accent: "#7c8c46",
  },
  {
    slug: "gallery-08",
    title: "Untitled",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 17" each (approx.)',
    year: "2024",
    image: "/images/gallery/gallery-08.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil-on-canvas diptych by Komal Hira, 2024",
    accent: "#6e4f52",
  },
  {
    slug: "gallery-09",
    title: "Solace 2",
    medium: "Oil on canvas",
    dimensions: '18 x 22" (approx.)',
    image: "/images/gallery/gallery-09.jpg",
    width: 2117,
    height: 2117,
    alt: "Solace 2, an oil painting by Komal Hira",
    accent: "#1f7a7a",
  },
  {
    slug: "gallery-10",
    title: "Untitled",
    medium: "Oil on canvas, diptych",
    dimensions: '12 x 18" and 8 x 12" (approx.)',
    year: "2024",
    image: "/images/gallery/gallery-10.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil-on-canvas diptych by Komal Hira, 2024",
    accent: "#d9a8ac",
  },
  {
    slug: "gallery-11",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '17 x 30" (approx.)',
    year: "2024",
    image: "/images/gallery/gallery-11.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil painting by Komal Hira, 2024",
    accent: "#c98a3e",
  },
  {
    slug: "gallery-12",
    title: "The Moment of Feel I",
    medium: "Oil on canvas, diptych",
    dimensions: '8 x 18"',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Lahore",
    image: "/images/gallery/gallery-12.jpg",
    width: 2117,
    height: 2117,
    alt: "The Moment of Feel I, an oil-on-canvas diptych by Komal Hira, 2022",
    accent: "#1f8a7a",
  },
  {
    slug: "gallery-13",
    title: "The Moment of Feel II",
    medium: "Oil on canvas, diptych",
    dimensions: '(1) 1.6 x 6.5", (2) 12 x 14"',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Lahore",
    image: "/images/gallery/gallery-13.jpg",
    width: 2117,
    height: 2117,
    alt: "The Moment of Feel II, an oil-on-canvas diptych by Komal Hira, 2022",
    accent: "#6b3f52",
  },
  {
    slug: "gallery-14",
    title: "The Blue Sky",
    medium: "Oil on canvas, diptych",
    dimensions: '8 x 16" each',
    year: "2023",
    collection: "Private collection",
    image: "/images/gallery/gallery-14.jpg",
    width: 2117,
    height: 2117,
    alt: "The Blue Sky, an oil-on-canvas diptych by Komal Hira, 2023",
    accent: "#2f8fa6",
  },
  {
    slug: "gallery-15",
    title: "Sigh",
    medium: "Oil on canvas, diptych",
    dimensions: '12 x 36" and 8 x 12" (approx.)',
    year: "2023",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/gallery-15.jpg",
    width: 2117,
    height: 2117,
    alt: "Sigh, an oil-on-canvas diptych by Komal Hira, 2023",
    accent: "#1f6b45",
  },
  {
    slug: "gallery-16",
    title: "Mindfulness",
    medium: "Oil on canvas",
    dimensions: '24 x 24" (approx.)',
    year: "2023",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/gallery-16.jpg",
    width: 2117,
    height: 2117,
    alt: "Mindfulness, an oil painting by Komal Hira, 2023",
    accent: "#2b2f57",
  },
  {
    slug: "gallery-17",
    title: "Untitled",
    medium: "Oil on canvas",
    dimensions: '8 x 48"',
    year: "2022",
    image: "/images/gallery/gallery-17.jpg",
    width: 2117,
    height: 2117,
    alt: "Untitled oil painting by Komal Hira, 2022",
    accent: "#c96b5c",
  },
  {
    slug: "gallery-18",
    title: "The Moment of Feel IV",
    medium: "Oil on canvas, diptych",
    dimensions: '10 x 30" each',
    year: "2022",
    collection: "Permanent collection, Ambiance Hotel Hunza",
    image: "/images/gallery/gallery-18.jpg",
    width: 2117,
    height: 2117,
    alt: "The Moment of Feel IV, an oil-on-canvas diptych by Komal Hira, 2022",
    accent: "#9c2a5e",
  },
  {
    slug: "gallery-19",
    title: "The Moment of Feel III",
    medium: "Oil on canvas",
    dimensions: '8 x 18" (approx.)',
    year: "2023",
    collection: "Private collection",
    image: "/images/gallery/gallery-19.jpg",
    width: 2117,
    height: 2117,
    alt: "The Moment of Feel III, an oil painting by Komal Hira, 2023",
    accent: "#3f8fbf",
  },
];

export function getPaintingBySlug(slug: string): Painting | undefined {
  return paintings.find((p) => p.slug === slug);
}
